# Example run macro for qsim

# Set run mode
/qsim/fSourceMode 2

/run/initialize 
/process/optical/boundary/setInvokeSD true

/qsim/filename rootfiles/qsim_out_MollerOpenElectron1.root
#/qsim/seed 50 

/qsim/zmin -41.0 mm
/qsim/zmax -41.0 mm

# /qsim/evgenfilename /Users/sudip/moller/softwares/qsim-zone/qsim-moller/InputEventDistribution/smEvGen_moller_open_gamma.root
/qsim/evgenfilename InputEventDistribution/smEvGen_moller_open_electron.root
#/qsim/evgenfilename InputEventDistribution/smEvGen_moller_open_gamma.root

/run/beamOn 15
